[0;34m10:49:20  "D:\Dmall_project\case\VC_project\connect_mysql.py:46"   操作异常: (1054, "Unknown column 'supplier_code' in 'where clause'") 
 [0m[0;34m10:49:21  "D:\Dmall_project\case\DF_project\DF_supplier\conftest.py:31"   9999 
 [0m[0;34m10:49:21  "D:\Dmall_project\case\DF_project\DF_supplier\conftest.py:32"   后置操作 
 [0m[0;34m10:49:21  "D:\Dmall_project\case\DF_project\df_testlogin.py:37"   <Response [200]> 
 [0m[0;32m2020-11-04 10:49:21 - api - "D:\Dmall_project\case\DF_project\DF_supplier\supplier.py:323" - add_supplier_cards - DEBUG -  返回日志：{'code': 0, 'data': '操作成功', 'message': None, 'succ': True}[0m
[0;32m2020-11-04 10:49:21 - api - "D:\Dmall_project\case\DF_project\DF_supplier\supplier.py:342" - approve_supplier_card - DEBUG -  返回日志：{'code': 100, 'data': None, 'message': '網絡異常，請聯系系統管理員', 'succ': False}[0m
